version = 1
SPDX-PackageName = "architecture"
SPDX-PackageDownloadLocation = "https://github.com/openmfp/architecture"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and openMFP contributors and architecture contributors."
SPDX-License-Identifier = "Apache-2.0"
